---
abstract: 'Installer for libarchive'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.3601'
  Test::More: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-Libarchive-Installer
requires:
  perl: '5.006'
resources:
  bugtracker: https://github.com/plicease/alien-libarchive-installer/issues
  homepage: http://perl.wdlabs.com/Alien-Libarchive-Installer/
  repository: git://github.com/plicease/alien-libarchive-installer.git
version: '0.02'
